from operator import xor  as XOR
from operator import and_ as AND
from operator import or_  as OR

system = {
    'x00': True,
    'x01': False,
    'x02': False,
    'x03': True,
    'x04': True,
    'x05': True,
    'x06': False,
    'x07': False,
    'x08': True,
    'x09': True,
    'x10': False,
    'x11': True,
    'x12': False,
    'x13': False,
    'x14': True,
    'x15': True,
    'x16': True,
    'x17': True,
    'x18': False,
    'x19': False,
    'x20': False,
    'x21': False,
    'x22': True,
    'x23': True,
    'x24': True,
    'x25': True,
    'x26': True,
    'x27': True,
    'x28': False,
    'x29': True,
    'x30': True,
    'x31': False,
    'x32': True,
    'x33': False,
    'x34': False,
    'x35': False,
    'x36': False,
    'x37': True,
    'x38': True,
    'x39': False,
    'x40': False,
    'x41': False,
    'x42': False,
    'x43': True,
    'x44': True,
    'y00': True,
    'y01': True,
    'y02': True,
    'y03': True,
    'y04': False,
    'y05': False,
    'y06': False,
    'y07': False,
    'y08': False,
    'y09': True,
    'y10': False,
    'y11': True,
    'y12': False,
    'y13': False,
    'y14': True,
    'y15': False,
    'y16': False,
    'y17': False,
    'y18': False,
    'y19': True,
    'y20': False,
    'y21': False,
    'y22': False,
    'y23': False,
    'y24': False,
    'y25': True,
    'y26': True,
    'y27': False,
    'y28': True,
    'y29': False,
    'y30': True,
    'y31': False,
    'y32': True,
    'y33': True,
    'y34': False,
    'y35': True,
    'y36': True,
    'y37': True,
    'y38': False,
    'y39': True,
    'y40': False,
    'y41': True,
    'y42': True,
    'y43': False,
    'y44': True,

    'ncs': ('x07', AND, 'y07'),
    'wrf': ('y24', AND, 'x24'),
    'tsm': ('x19', XOR, 'y19'),
    'svt': ('x40', XOR, 'y40'),
    'dfv': ('rjf', OR , 'src'),
    'z44': ('fsf', XOR, 'fgs'),
    'qgn': ('mhc', AND, 'jqd'),
    'kpp': ('nrr', XOR, 'sms'),
    'ngc': ('y20', AND, 'x20'),
    'hbc': ('y21', AND, 'x21'),
    'rqf': ('sgj', OR , 'ptb'),
    'gjn': ('hbc', OR , 'wdr'),
    'z23': ('tks', XOR, 'sbg'),
    'hgg': ('ddh', AND, 'tnm'),
    'vbb': ('hsf', OR , 'bjw'),
    'vqs': ('x15', XOR, 'y15'),
    'dtm': ('x10', AND, 'y10'),
    'z15': ('vqs', XOR, 'vss'),
    'mgd': ('x29', XOR, 'y29'),
    'qtn': ('srg', OR , 'cwb'),
    'z45': ('nmb', OR , 'mbk'),
    'tng': ('dhs', OR , 'njq'),
    'vpd': ('jfw', OR , 'jrf'),
    'gck': ('x07', XOR, 'y07'),
    'z03': ('tdw', XOR, 'vrk'),
    'ffw': ('y11', AND, 'x11'),
    'bth': ('x16', XOR, 'y16'),
    'tnm': ('x39', XOR, 'y39'),
    'jrq': ('cfg', AND, 'ngh'),
    'hbj': ('vpd', AND, 'mvn'),
    'z16': ('rgp', XOR, 'bth'),
    'vrv': ('qtn', AND, 'cjd'),
    'cgt': ('x14', AND, 'y14'),
    'z24': ('dwh', XOR, 'hsk'),
    'z13': ('tgp', XOR, 'dkh'),
    'cfg': ('y26', XOR, 'x26'),
    'z42': ('cpc', XOR, 'nbm'),
    'cpc': ('y42', XOR, 'x42'),
    'cjd': ('x17', XOR, 'y17'),
    'z36': ('rqf', XOR, 'pqn'),
    'nwg': ('x27', AND, 'y27'),
    'vjp': ('bcq', AND, 'hnk'),
    'wqr': ('tks', AND, 'sbg'),
    'gmw': ('wvr', OR , 'skq'),
    'pqw': ('cwm', AND, 'tpv'),
    'tqh': ('x41', AND, 'y41'),
    'sbr': ('jcw', AND, 'wpk'),
    'tbh': ('tgp', AND, 'dkh'),
    'z38': ('wrg', XOR, 'nwq'),
    'gds': ('y32', XOR, 'x32'),
    'msb': ('bmn', OR , 'hbj'),
    'z33': ('wps', XOR, 'mtn'),
    'sws': ('ncs', OR , 'pjf'),
    'dwh': ('wqr', OR , 'tqk'),
    'pwg': ('x31', AND, 'y31'),
    'jcw': ('y12', XOR, 'x12'),
    'z31': ('nrr', AND, 'sms'),
    'npd': ('x38', AND, 'y38'),
    'fwt': ('y02', AND, 'x02'),
    'rnc': ('y37', AND, 'x37'),
    'tdw': ('fwt', OR , 'vtm'),
    'nwq': ('x38', XOR, 'y38'),
    'ckd': ('gds', AND, 'ghr'),
    'wpk': ('ffw', OR , 'nfb'),
    'z05': ('ctv', XOR, 'wht'),
    'cmg': ('y11', XOR, 'x11'),
    'ctv': ('y05', XOR, 'x05'),
    'z18': ('jhw', XOR, 'tcv'),
    'rmw': ('wrf', OR , 'gnt'),
    'tnr': ('y01', AND, 'x01'),
    'pqn': ('x36', XOR, 'y36'),
    'skp': ('gjq', OR , 'dfg'),
    'ptg': ('x40', AND, 'y40'),
    'dqn': ('y39', AND, 'x39'),
    'sbg': ('bjb', OR , 'hjf'),
    'qfs': ('rrn', OR , 'rpt'),
    'dhs': ('ctv', AND, 'wht'),
    'ccw': ('sgs', AND, 'rsb'),
    'z25': ('rmw', XOR, 'psg'),
    'hsk': ('y24', XOR, 'x24'),
    'z10': ('bgd', XOR, 'msb'),
    'fvv': ('y17', AND, 'x17'),
    'kdh': ('y22', AND, 'x22'),
    'fgp': ('qfs', AND, 'rfv'),
    'rhr': ('wds', AND, 'fps'),
    'tcv': ('y18', XOR, 'x18'),
    'tfw': ('ttd', AND, 'nhg'),
    'ptb': ('bbc', AND, 'jkb'),
    'cpb': ('djn', OR , 'tnr'),
    'bbc': ('y35', XOR, 'x35'),
    'z14': ('tfw', OR , 'cgt'),
    'srg': ('rgp', AND, 'bth'),
    'gnt': ('dwh', AND, 'hsk'),
    'frt': ('pqw', OR , 'ngc'),
    'psg': ('y25', XOR, 'x25'),
    'tgp': ('y13', XOR, 'x13'),
    'rbw': ('x30', XOR, 'y30'),
    'jhw': ('vrv', OR , 'fvv'),
    'z29': ('skp', XOR, 'mgd'),
    'z11': ('cmg', XOR, 'ntv'),
    'z04': ('vjr', XOR, 'vbb'),
    'z08': ('gkj', XOR, 'sws'),
    'tpv': ('x20', XOR, 'y20'),
    'nfb': ('ntv', AND, 'cmg'),
    'tdk': ('x32', AND, 'y32'),
    'vtm': ('wmr', AND, 'cpb'),
    'jps': ('x19', AND, 'y19'),
    'rqv': ('jhw', AND, 'tcv'),
    'bcq': ('y27', XOR, 'x27'),
    'hdk': ('x34', AND, 'y34'),
    'z01': ('wqc', XOR, 'qtf'),
    'dkh': ('wgk', OR , 'sbr'),
    'kdb': ('x43', AND, 'y43'),
    'vjr': ('y04', XOR, 'x04'),
    'fgg': ('rmw', AND, 'psg'),
    'jfw': ('gkj', AND, 'sws'),
    'z20': ('cwm', XOR, 'tpv'),
    'z17': ('cjd', XOR, 'qtn'),
    'nmb': ('fsf', AND, 'fgs'),
    'rpt': ('wps', AND, 'mtn'),
    'mtn': ('x33', XOR, 'y33'),
    'z27': ('bcq', XOR, 'hnk'),
    'nhg': ('tbh', OR , 'wwk'),
    'z19': ('twb', XOR, 'tsm'),
    'wdr': ('frt', AND, 'mhw'),
    'pwr': ('y15', AND, 'x15'),
    'z30': ('rbw', XOR, 'dfv'),
    'ctt': ('vss', AND, 'vqs'),
    'gjq': ('x28', AND, 'y28'),
    'dvf': ('y28', XOR, 'x28'),
    'sgj': ('bbc', XOR, 'jkb'),
    'fps': ('x43', XOR, 'y43'),
    'khw': ('y04', AND, 'x04'),
    'ghr': ('pwg', OR , 'kpp'),
    'nrr': ('x31', XOR, 'y31'),
    'z07': ('gmw', XOR, 'gck'),
    'z21': ('frt', XOR, 'mhw'),
    'skq': ('spb', AND, 'tng'),
    'knf': ('svt', AND, 'hkg'),
    'bjb': ('gjn', AND, 'kdh'),
    'z34': ('qfs', XOR, 'rfv'),
    'jtt': ('cpc', AND, 'nbm'),
    'nbm': ('tqh', OR , 'ccw'),
    'wds': ('jtt', OR , 'qkv'),
    'z32': ('gds', XOR, 'ghr'),
    'qnv': ('rbw', AND, 'dfv'),
    'gjr': ('msb', AND, 'bgd'),
    'sms': ('qnv', OR , 'bjd'),
    'pns': ('y18', AND, 'x18'),
    'rsb': ('x41', XOR, 'y41'),
    'srh': ('x26', AND, 'y26'),
    'ddh': ('nvc', OR , 'npd'),
    'ntv': ('dtm', OR , 'gjr'),
    'jrf': ('x08', AND, 'y08'),
    'ttd': ('y14', XOR, 'x14'),
    'wvr': ('y06', AND, 'x06'),
    'cwb': ('y16', AND, 'x16'),
    'wrg': ('rnc', OR , 'qgn'),
    'bjd': ('y30', AND, 'x30'),
    'z37': ('jqd', XOR, 'mhc'),
    'z39': ('ddh', XOR, 'tnm'),
    'wgk': ('x12', AND, 'y12'),
    'ngh': ('cqh', OR , 'fgg'),
    'z22': ('kdh', XOR, 'gjn'),
    'wqc': ('x01', XOR, 'y01'),
    'wht': ('khw', OR , 'djm'),
    'rgp': ('ctt', OR , 'pwr'),
    'mhw': ('y21', XOR, 'x21'),
    'dhh': ('vjp', OR , 'nwg'),
    'wmr': ('x02', XOR, 'y02'),
    'pjf': ('gck', AND, 'gmw'),
    'twb': ('rqv', OR , 'pns'),
    'qtf': ('y00', AND, 'x00'),
    'njq': ('y05', AND, 'x05'),
    'rjf': ('y29', AND, 'x29'),
    'hsf': ('vrk', AND, 'tdw'),
    'qkv': ('y42', AND, 'x42'),
    'bgd': ('y10', XOR, 'x10'),
    'z26': ('cfg', XOR, 'ngh'),
    'z06': ('tng', XOR, 'spb'),
    'z00': ('y00', XOR, 'x00'),
    'z02': ('cpb', XOR, 'wmr'),
    'wps': ('ckd', OR , 'tdk'),
    'hnk': ('jrq', OR , 'srh'),
    'hjf': ('y22', XOR, 'x22'),
    'bjw': ('x03', AND, 'y03'),
    'vss': ('nhg', XOR, 'ttd'),
    'rwg': ('tsm', AND, 'twb'),
    'hkg': ('dqn', OR , 'hgg'),
    'rfv': ('y34', XOR, 'x34'),
    'z35': ('y35', AND, 'x35'),
    'cqh': ('x25', AND, 'y25'),
    'rrn': ('y33', AND, 'x33'),
    'djn': ('wqc', AND, 'qtf'),
    'z41': ('sgs', XOR, 'rsb'),
    'gkj': ('x08', XOR, 'y08'),
    'cwm': ('rwg', OR , 'jps'),
    'wbv': ('rqf', AND, 'pqn'),
    'mhc': ('x37', XOR, 'y37'),
    'z28': ('dvf', XOR, 'dhh'),
    'fgs': ('kdb', OR , 'rhr'),
    'sgs': ('knf', OR , 'ptg'),
    'z40': ('svt', XOR, 'hkg'),
    'wwk': ('y13', AND, 'x13'),
    'tqk': ('y23', AND, 'x23'),
    'jkb': ('fgp', OR , 'hdk'),
    'z12': ('jcw', XOR, 'wpk'),
    'spb': ('y06', XOR, 'x06'),
    'tks': ('x23', XOR, 'y23'),
    'bmn': ('y09', AND, 'x09'),
    'z43': ('wds', XOR, 'fps'),
    'dfg': ('dhh', AND, 'dvf'),
    'src': ('mgd', AND, 'skp'),
    'nvc': ('wrg', AND, 'nwq'),
    'vrk': ('y03', XOR, 'x03'),
    'kqk': ('y36', AND, 'x36'),
    'djm': ('vjr', AND, 'vbb'),
    'fsf': ('x44', XOR, 'y44'),
    'mbk': ('x44', AND, 'y44'),
    'jqd': ('kqk', OR , 'wbv'),
    'z09': ('vpd', XOR, 'mvn'),
    'mvn': ('y09', XOR, 'x09'),
}